services:
    nginx:
        build:
            context: .
        ports:
            - '9888:80'
            - '450:443'
            - '1935:1935'
        restart: unless-stopped
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
